# Generated by Django 5.2 on 2025-05-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_post_roomrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
