# Generated by Django 5.2 on 2025-06-06 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingconfirmation',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
